---
title: "Discussion of Hernán et al (2008)"
author: "Jean Morrison"
institute: "University of Michigan"
date: "2022-02-09 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
# Introduction

- What is the main causal question?
  - Define the exposure
  - Define the outcome

- Are there any secondary questions?

- Who is the population being studied?

---
# Study Design

- What is the structure of the NHS study?

- Who is included, who is excluded and why?

---
# DAG

- Draw a DAG of the problem as conceptualized by the authors. 

  + Include exposure, outcome, confounders
  + Include selection into the trial
  
- For now, ignore adherence.
  
---
# ITT Analysis

- How do the authors estimate the ITT effect in a single "trial"?

- What are the multiple "trials"?

- How is analysis combined across multiple "trials"?

- What is the proposed alternative to the proportional hazards analysis?

---

# Results of ITT Analysis

- Look at Table 3 together + paragraph  on Page 4

- Look at Figure 2

- How does Table 3 compare to Table 4?

---

# Adherence

- How is adherence vs non-adherence defined?

- Expand the DAG to include outcomes $Y_1, \dots, Y_k$ and adherence and censoring at each time point. 

- What are the counterfactuals in the adherence-adjusted and non-adherence adjusted analyses?

- How do the authors conduct the adherence-adjusted analysis?



---

# Results of Adherence Adjusted Analysis 

- Look at Table 5 and Figure 4

---
# Results of ITT Analysis

- How do the results compare to the previous NHS analysis?

- Look at Table 6 together

- How does column (i) compare to column (ii)

- How does column (iii) compare to cols (i) and (ii)?

- Columns (iv), (v), (vi)

---
# Discussion

- Comments, questions, opintions?

- Which method do you most prefer?

- What would you do differently?



$\newcommand{\ci}{\perp\!\!\!\perp}$

