---
title: "L0: Course Orientation"

author: "Jean Morrison"
institute: "University of Michigan"
date: "2021-01-05 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

# Welcome + Course Basics

+ We will meet twice a week in person:
  - Monday's 1-2:30 in M1152 SPH II
  - Wednesday's 1-2:30 in M3755 SPH I

+ Textbook: 
  - ["What If?" By Miguel Hernán and James Robins](https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/) 
  - Other readings will be provided as pdfs

---

# Course Structure

< Tour of Canvas Site >

---

# What is Causal Inference?

--

+ Causal inference is the art and science of using statistical tools to answer causal questions. 

--


+ Interpreting statistical parameters as causal parameters requires:

  - A language and philosophy of causality.
  - A model of the system you are studying.


---

# What We Will Learn in this Class

--

+ Languages of causality:

  - Counterfactuals and Potential Outcomes
  - Graphical models
  - Structural Equation Models

--

+ Identifiability conditions 

--

+ Estimation strategies:
  - Weighting, standardization, G-estimation
  - Propensity scores and matching
  - Instrumental variable analysis
  - Methods for time-varying treatment
  -...


---

# About Me

- Jean Morrison. You can call me Jean (or Dr. Morrison if you prefer).

- My pronouns are they/them. 

- Research:
  + Statistical genetics
  + Instrumental variable analysis with genetic instruments
  + High dimensional biological data
  + Data integration (combining multiple sources of Hi-D data)


---

# About This Class

- This is the first teaching of this variation of this class!

- Please tell me what you like and what you don't like.

- Plans may change as the semester progresses.

- I will teach it again next year: If you are auditing because you don't have 
time this year, consider taking the class next year. 


---

# About This Class

- The goal is to create an active, collaborative, learning environment. 

- Ground rules: 
  + Be engaged, ask questions, and contribute to discussions.
  + Complete assignments on schedule. 
  + Be respectful of me and your classmates. 


---

# Covid Contingency Plans

- The class is in-person unless the University changes course.
--


  + I do not control this.

--


- There will always be a Zoom option:

  + Let me know ahead of time if you are planning to Zoom. 
  + Use the Zoom option for circumstances when you really can't be here
  (i.e. you or your family are sick, an emergency has kept you home, travel disruptions).
  + You don't have to tell me why you are zooming in.
  
---

# Covid Contingency Plans

- If you are sick or test positive: 
  + Don't come to class, zoom in if you feel well enough.
  + Watch lectures asynchronously if needed. 
  + Let me know.
  
- If I am sick or test positive:
  + If I test positive but am not symptomatic, class will be held by zoom. 
  + We may have to do asynchronous lectures, or I will ask someone to fill in. 

- Hopefully we all stay healthy.
 
 
 
---

# Intro Survey

Please fill out [the introductory survey](https://forms.gle/EfComH5FDyTovbf79) by Friday. 
